import React from "react";
import { type NextPage } from "next";
import { useAppDispatch } from '@utils/store'
import Head from "next/head";
import MoviesList from "@components/movie/movies-list/MoviesList";
import TrendingMovies from "@components/movie/trending/TrendingMovies";
import { fetchGenres, fetchMovies, MoviesQueryReturn } from '@utils/query'
import { GenreList, setGenre } from "@utils/store/slices/genreSlice";
import { setMovies } from "@utils/store/slices/moviesSlice";
import { setTrending } from "@utils/store/slices/trendingSlice";

interface HomePageProps {
  genres: GenreList
  movies: MoviesQueryReturn
  trending: MoviesQueryReturn
}

export async function getServerSideProps(){
  const popular = "movie/popular"
  const trendingPath = 'trending/movie/week'
  const genres = await fetchGenres()
  const movies = await fetchMovies(popular) 
  const trending = await fetchMovies(trendingPath) 
  return {
    props: {
      genres,
      movies,
      trending
    }
  }
}

const Home: NextPage<HomePageProps> = (props) => {
  const { genres, movies, trending } = props
  const dispatch = useAppDispatch()
  dispatch(setGenre({result: genres}))
  dispatch(setMovies(movies))
  dispatch(setTrending(trending))

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-2 gap-3 flex flex-col">
        <TrendingMovies />
        <MoviesList />
      </main>
    </>
  );
};

export default Home;
